import { User } from '../models/user.model';

export const DEFAULT_USER: User = {
  email: 'mockuser@email.com',
  name: 'John Doe',
  password: 'password',
  accounts: [
    {
      accountNo: '1',
      balance: Math.round(Math.random() * 10 ** 4),
      ownerName: 'John Doe',
      transactionHistory: [
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-01'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '1',
        },
        {
          action: 'SENT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-07'),
          from: 'John Doe',
          to: 'Jane Doe',
          transactionNo: '2',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-23'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '3',
        },
      ],
    },
    {
      accountNo: Math.round(Math.random() * 10 ** 6).toString(),
      balance: 3500,
      ownerName: 'John Doe',
      transactionHistory: [
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-13'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '4',
        },
        {
          action: 'SENT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-19'),
          from: 'John Doe',
          to: 'Jane Doe',
          transactionNo: '5',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-07'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '7',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-09'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '8',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-10'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '9',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-15'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '10',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-16'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '16',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-17'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '17',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-18'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '18',
        },
        {
          action: 'RECEIVED',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-19'),
          from: 'Jane Doe',
          to: 'John Doe',
          transactionNo: '19',
        },
      ],
    },
    {
      accountNo: Math.round(Math.random() * 10 ** 6).toString(),
      balance: Math.round(Math.random() * 10 ** 4),
      ownerName: 'John Doe',
      transactionHistory: [],
    },
    {
      accountNo: Math.round(Math.random() * 10 ** 6).toString(),
      balance: Math.round(Math.random() * 10 ** 4),
      ownerName: 'John Doe',
      transactionHistory: [],
    },
    {
      accountNo: Math.round(Math.random() * 10 ** 6).toString(),
      balance: Math.round(Math.random() * 10 ** 4),
      ownerName: 'John Doe',
      transactionHistory: [],
    },
    {
      accountNo: Math.round(Math.random() * 10 ** 6).toString(),
      balance: Math.round(Math.random() * 10 ** 4),
      ownerName: 'John Doe',
      transactionHistory: [],
    },
  ],
};
