import { User } from '../models/user.model';

export const DEFAULT_USER: User = {
  email: 'mockuser@email.com',
  fullname: 'John Doe',
  password: 'password',
  accounts: [
    {
      id: '1',
      label: 'Main TL',
      currency: 'TL',
      balance: Math.round(Math.random() * 10 ** 4),
      transactions: [
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-01'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '1',
        },
        {
          action: 'SENT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-07'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '2',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-23'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '3',
        },
      ],
    },
    {
      id: Math.round(Math.random() * 10 ** 6).toString(),
      balance: 3500,
      currency: 'DOLLAR',
      label: 'Main Dollar',
      transactions: [
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-13'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '4',
        },
        {
          action: 'SENT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-08-19'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '5',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-07'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '7',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-09'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '8',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-10'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '9',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-15'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '10',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-16'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '16',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-17'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '17',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-18'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '18',
        },
        {
          action: 'GOT',
          amount: Math.round(Math.random() * 1000),
          date: new Date('2021-09-19'),
          otherPerson: {
            id: '2',
            accountNo: '12345',
            email: 'janedoe@gmail.com',
            name: 'janedoe',
          },
          id: '19',
        },
      ],
    },
    {
      id: Math.round(Math.random() * 10 ** 6).toString(),
      label: 'Main Euro',
      currency: 'EURO',
      balance: Math.round(Math.random() * 10 ** 4),
      transactions: [],
    },
    {
      id: Math.round(Math.random() * 10 ** 6).toString(),
      label: 'Main Euro',
      currency: 'EURO',
      balance: Math.round(Math.random() * 10 ** 4),
      transactions: [],
    },
    {
      id: Math.round(Math.random() * 10 ** 6).toString(),
      label: 'Main Euro',
      currency: 'EURO',
      balance: Math.round(Math.random() * 10 ** 4),
      transactions: [],
    },
  ],
};
